// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJDz0d-agtSWmEAupwEc2lUI9zST4-6w',
    appId: '1:843564247946:web:cd2be2188bda2776433673',
    messagingSenderId: '843564247946',
    projectId: 'shoppingapp-21ccf',
    authDomain: 'shoppingapp-21ccf.firebaseapp.com',
    storageBucket: 'shoppingapp-21ccf.firebasestorage.app',
    measurementId: 'G-LSYHGJXX74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGQ8VNPgiyFkCY0uZ5XZt2yBWAbxDzYiY',
    appId: '1:843564247946:android:6cc5ec452bad5fb7433673',
    messagingSenderId: '843564247946',
    projectId: 'shoppingapp-21ccf',
    storageBucket: 'shoppingapp-21ccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQadO4O4c_DRj6O-W1UxnxX7Yslu9zdiU',
    appId: '1:843564247946:ios:51ef962caae3fd44433673',
    messagingSenderId: '843564247946',
    projectId: 'shoppingapp-21ccf',
    storageBucket: 'shoppingapp-21ccf.firebasestorage.app',
    iosClientId: '843564247946-7c32ivfvlvh95vp65hu8huhjpc3j6573.apps.googleusercontent.com',
    iosBundleId: 'com.example.eshopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQadO4O4c_DRj6O-W1UxnxX7Yslu9zdiU',
    appId: '1:843564247946:ios:51ef962caae3fd44433673',
    messagingSenderId: '843564247946',
    projectId: 'shoppingapp-21ccf',
    storageBucket: 'shoppingapp-21ccf.firebasestorage.app',
    iosClientId: '843564247946-7c32ivfvlvh95vp65hu8huhjpc3j6573.apps.googleusercontent.com',
    iosBundleId: 'com.example.eshopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWJDz0d-agtSWmEAupwEc2lUI9zST4-6w',
    appId: '1:843564247946:web:be9a963115ac691e433673',
    messagingSenderId: '843564247946',
    projectId: 'shoppingapp-21ccf',
    authDomain: 'shoppingapp-21ccf.firebaseapp.com',
    storageBucket: 'shoppingapp-21ccf.firebasestorage.app',
    measurementId: 'G-JECYVQL94X',
  );

}